# backend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: academic-hub-backend
  labels:
    app: academic-hub-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: academic-hub-backend
  template:
    metadata:
      labels:
        app: academic-hub-backend
    spec:
      containers:
        - name: backend
          image: academic-hub-backend:latest
          imagePullPolicy: Never # Add this line
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secrets
          resources:
            requests:
              memory: "512Mi"
              cpu: "200m"
            limits:
              memory: "1Gi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: academic-hub-backend-service
spec:
  selector:
    app: academic-hub-backend
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
