# backend-config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://academic-hub-postgres:5432/academic_hub_db # Updated to match postgres service
  SPRING_JPA_HIBERNATE_DDL_AUTO: validate
  SPRING_JPA_SHOW_SQL: "true"
  SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
  SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"

  SPRING_FLYWAY_ENABLED: "true"
  SPRING_FLYWAY_BASELINE_ON_MIGRATE: "true"
  SPRING_FLYWAY_LOCATIONS: classpath:db/migration

  JWT_ISSUER: "Academic Hub"
  JWT_TOKEN_EXPIRATION: "3600000"
  JWT_REFRESH_TOKEN_EXPIRATION: "604800000"

  SPRING_MAIL_HOST: smtp.gmail.com
  SPRING_MAIL_PORT: "587"
  SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: "true"
  SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: "true"

  APP_FRONTEND_URL: http://academic-hub-frontend-service # Updated to match frontend service
