apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
data:
  JWT_SECRET: bzA1MmoxOW5tQ1BIWGV3Z0FqT1lvME1xNCs4cjlvTU44eTlDMU1OczFqQzBnUlFmTDlGMzNyazZBb2lKWko4M01KV0hmaFA3SGp0L0dQellj
  SPRING_MAIL_USERNAME: ZmEucmVzZWFyY2gxMDQ4QGdtYWlsLmNvbQ==
  SPRING_MAIL_PASSWORD: Y3V2aGV1aXVjamtiYnZ5dQ==