# ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: academic-hub-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - host: academic-hub.local
      http:
        paths:
          - path: /()(.*)
            pathType: Prefix
            backend:
              service:
                name: academic-hub-frontend-service
                port:
                  number: 80
          - path: /api(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: academic-hub-backend-service
                port:
                  number: 8080
