apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
type: Opaque
data:
  POSTGRES_PASSWORD: MjczMDAx  # base64 encoded 'academic_hub_password'
  POSTGRES_USER: cG9zdGdyZXM=  # base64 encoded 'academic_hub_user'