# postgres-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: academic-hub-postgres
  labels:
    app: academic-hub-postgres
spec:
  selector:
    app: academic-hub-postgres
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP
